### ISSUE TITLE
HTTP/3 Tutorial: curl installation instructions do not work

### ISSUE THREAD

**Issue by sharpobject** [cloudflare/cloudflare-docs#2970]
At https://developers.cloudflare.com/http3/tutorials/curl-brew the user is instructed to install a certain version of curl using homebrew.

### Expected Behavior
The installation succeeds.

### Actual Behavior
```
$ brew install --HEAD -s curl.rb
Error: Failed to load cask: curl.rb
Cask 'curl' is unreadable: wrong constant name #<Class:0x0000000131ae5a60>
Warning: Treating curl.rb as a formula.
==> Cloning https://github.com/curl/curl.git
Cloning into '/Users/sharpobject/Library/Caches/Homebrew/curl--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> autoreconf -fi
==> git clone --recursive https://github.com/cloudflare/quiche
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
Cargo.toml:
  expected replacement of /^crate-type = .*/ with "crate-type = [\"staticlib\"]"
```

**Comment by kodster28** [comment]
Howdy @LPardue, is this something you'd be able to help with?

**Comment by Njones11x** [comment]
I believe it was broken by this 

https://github.com/cloudflare/quiche/commit/bbe6e2ab22126773bb63e4605ac4c8e7594f002a

**Comment by LPardue** [comment]
Yeah that's most likely it, just need to tweak a few things to make it consistent with the new layout. Sorry we missed this

**Comment by junhochoi** [comment]
I'll take a look.

**Comment by x2q** [comment]
+1

**Comment by junhochoi** [comment]
I made a PR for updating homebrew formula: https://github.com/cloudflare/homebrew-cloudflare/pull/43
```brew install --HEAD -d -s ./curl.rb``` will install curl 7.81.0 + quiche master.

Building from curl master (`--HEAD`) builds ok but it need `-k` when using `--http3`. looking

**Comment by junhochoi** [comment]
The problem above is solved and curl master + quiche master works ok. Anyone can try?

**Comment by junhochoi** [comment]
Can anyone verify https://github.com/cloudflare/homebrew-cloudflare/pull/43 works?
If it works I will merge it.

@sharpobject @Njones11x @x2q

**Comment by junhochoi** [comment]
cloudflare/homebrew-cloudflare#43 is merged. No changes needed on the documentation.

**Comment by cj-scott-prive** [comment]
It looks like this documentation has been removed? : https://developers.cloudflare.com/http3/tutorials/curl-brew now just redirects to HTTP/3 info.

Since HTTP3 support still isn't mainstreamed into the Curl project, the cloudflare patch and docs for Mac Homebrew are quite useful. Thanks
